steps:

  - command:
    - auto/generate_release_notes.sh
    - auto/build.sh
    - auto/deploy_dev.sh
    - auto/generate_version_file.sh
    label: ":package: & :rocket: Build & Deploy Dev: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: dev devops
    agents:
      queue: "wo:nonprod"
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "dev"

  - command:
    - auto/generate_release_notes.sh
    - auto/build.sh
    - auto/deploy_qa.sh
    - auto/generate_version_file.sh
    label: ":package: & :rocket: Build & Deploy QA: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: master
    agents:
      queue: "wo:nonprod"
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "qa"    

  - wait

  - block: ":green_button: Deploy to PROD"
    prompt: "Deploy WO to PROD environment?"
    branches: "master"

  - command: 
    - auto/generate_release_notes.sh
    - auto/build.sh
    - auto/deploy_prod.sh
    - auto/generate_version_file.sh
    label: ":package: & :rocket: Build & Deploy PROD: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: master
    agents:
      queue: "wo:prod"
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "prod"    
